// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt0L_4BjMTfBH0vidYrLbaUqUpMvsqTcU',
    appId: '1:620834252127:web:135a2cf79ab841d43e82ea',
    messagingSenderId: '620834252127',
    projectId: 'three-youth-app',
    authDomain: 'three-youth-app.firebaseapp.com',
    storageBucket: 'three-youth-app.appspot.com',
    measurementId: 'G-SCVTXNB05N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp37SGKg2aX-8PhDH1ty33LVRgNbIslLs',
    appId: '1:620834252127:android:a3f911ecde775c413e82ea',
    messagingSenderId: '620834252127',
    projectId: 'three-youth-app',
    storageBucket: 'three-youth-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYFopIuPWupDdI_FerGgaydUZFW81jpRw',
    appId: '1:620834252127:ios:601facd5c10724ce3e82ea',
    messagingSenderId: '620834252127',
    projectId: 'three-youth-app',
    storageBucket: 'three-youth-app.appspot.com',
    iosClientId:
        '620834252127-gfep92avvtggm430a2bb4amno7svjrrt.apps.googleusercontent.com',
    iosBundleId: 'com.three-youth-app.bleapp',
  );
}
