// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5cQhYZWWIpo8tSEJcGL4-PkowMBgtSiA',
    appId: '1:409696307486:android:2a0df5041537c7d10b610f',
    messagingSenderId: '409696307486',
    projectId: 'running-heart-4faf0',
    storageBucket: 'running-heart-4faf0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuF3gc93-k0dxJiB8-S3494w0l4ZK--ig',
    appId: '1:409696307486:ios:4197db4204fad9170b610f',
    messagingSenderId: '409696307486',
    projectId: 'running-heart-4faf0',
    storageBucket: 'running-heart-4faf0.appspot.com',
    androidClientId: '409696307486-te1f1q07h0g579l5pcsvvorjchdhrpf8.apps.googleusercontent.com',
    iosClientId: '409696307486-0i4upd92pr212rj0di01jliole2v7jcu.apps.googleusercontent.com',
    iosBundleId: 'com.threeyouth.runningHeart',
  );
}
